import Navbar from "@/components/ui/Navbar";
import "@/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
// import { type Metadata } from "next";
// import { Inter } from "next/font/google";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className={`${inter.className}`}>
//       <body>{children}</body>
//     </html>
//   );
// }

// import "./globals.css";
// import muiTheme from "./muiTheme";
import { Inter } from "next/font/google";
// import CssBaseline from "@mui/material/CssBaseline";
// import { ThemeProvider } from "@mui/material/styles";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AppRouterCacheProvider options={{ enableCssLayer: true }}> */}
        {/* <ThemeProvider theme={muiTheme}> */}
        {/* <CssBaseline /> */}
        <Navbar />
        <main>{children}</main>
        {/* {children} */}
        {/* </ThemeProvider> */}
        {/* </AppRouterCacheProvider> */}
      </body>
    </html>
  );
}
